In [2]:
import torch

In [3]:
print(torch.__version__)

2.6.0+cu124


In [4]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU Tesla T4


In [5]:
## Creating a Tensor

#using empty 
a = torch.empty(2,3)

In [6]:
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
type(a)

torch.Tensor

In [8]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.rand(2,3)

tensor([[0.5289, 0.4814, 0.9696],
        [0.4979, 0.6289, 0.5196]])

In [12]:
torch.rand(2,3)

tensor([[0.4447, 0.7299, 0.9871],
        [0.7705, 0.3197, 0.9065]])

In [14]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [15]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [16]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [18]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [19]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [20]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [21]:
## Tensors Shapes

In [25]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [26]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [27]:
x.shape

torch.Size([2, 3])

In [28]:
torch.empty_like(x)

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 7233967582392366899]])

In [29]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [30]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [32]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [33]:
### Tensors Data Types

In [34]:
x.dtype

torch.int64

In [35]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [36]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [37]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [39]:
### Mathematical Operations

In [40]:
## 1.Scaler Operation
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [41]:
x+2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [42]:
x -2 

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [43]:
x*3

tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [44]:
x/3

tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])

In [45]:
((x*100)//3)%2

tensor([[1., 0.],
        [1., 0.]])

In [46]:
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

In [47]:
# 2.Element wise operation

In [48]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [49]:
a,b

(tensor([[0.9969, 0.7565, 0.2239],
         [0.3023, 0.1784, 0.8238]]),
 tensor([[0.5557, 0.9770, 0.4440],
         [0.9478, 0.7445, 0.4892]]))

In [50]:
a+b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [51]:
a-b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [52]:
a*b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [53]:
a/b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [54]:
a**b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [55]:
a%b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [56]:
c = torch.tensor([1,-2,3,-4])

In [57]:
c

tensor([ 1, -2,  3, -4])

In [58]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [59]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [60]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [61]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [62]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [63]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [64]:
torch.clamp(d, min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [65]:
# 3. Reduction Operation


In [66]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)

In [67]:
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [68]:
torch.sum(e)

tensor(24.)

In [69]:
torch.sum(e, dim=0)

tensor([ 8.,  0., 16.])

In [70]:
torch.sum(e, dim=1)

tensor([15.,  9.])

In [71]:
torch.mean(e)

tensor(4.)

In [72]:
torch.mean(e, dim=0)

tensor([4., 0., 8.])

In [73]:
torch.median(e)

tensor(0.)

In [74]:
torch.max(e)

tensor(9.)

In [75]:
torch.min(e)

tensor(0.)

In [76]:
torch.prod(e)

tensor(0.)

In [77]:
torch.std(e)

tensor(4.4272)

In [78]:
torch.var(e)

tensor(19.6000)

In [79]:
torch.argmax(e)

tensor(5)

In [80]:
torch.argmin(e)

tensor(1)

In [81]:
# 4. Matrix Operations

In [83]:
f = torch.randint(size=(2,3),low=0,high=10)
g = torch.randint(size=(3,2),low=0,high=10)

In [84]:
print(f)

tensor([[5, 9, 8],
        [9, 7, 9]])


In [85]:
print(g)

tensor([[2, 6],
        [7, 7],
        [8, 3]])


In [86]:
torch.matmul(f,g)

tensor([[137, 117],
        [139, 130]])

In [87]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

In [88]:
torch.dot(vector1,vector2)

tensor(11)

In [90]:
torch.transpose(f,0,1)

tensor([[5, 9],
        [9, 7],
        [8, 9]])

In [91]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[6., 1., 5.],
        [5., 0., 4.],
        [3., 8., 8.]])

In [92]:
torch.det(h)

tensor(-20.0000)

In [93]:
torch.inverse(h)

tensor([[ 1.6000, -1.6000, -0.2000],
        [ 1.4000, -1.6500, -0.0500],
        [-2.0000,  2.2500,  0.2500]])

In [94]:
# 5. Comparison Operations

In [95]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[3, 3, 5],
        [0, 6, 4]])
tensor([[0, 8, 4],
        [7, 2, 3]])


In [96]:
i > j

tensor([[ True, False,  True],
        [False,  True,  True]])

In [97]:
i < j

tensor([[False,  True, False],
        [ True, False, False]])

In [98]:
i == j

tensor([[False, False, False],
        [False, False, False]])

In [99]:
i != j

tensor([[True, True, True],
        [True, True, True]])

In [100]:
# 6. Special functions

In [101]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[8., 5., 6.],
        [2., 9., 5.]])

In [102]:
torch.log(k)

tensor([[2.0794, 1.6094, 1.7918],
        [0.6931, 2.1972, 1.6094]])

In [103]:
torch.exp(k)

tensor([[2.9810e+03, 1.4841e+02, 4.0343e+02],
        [7.3891e+00, 8.1031e+03, 1.4841e+02]])

In [104]:
torch.sqrt(k)

tensor([[2.8284, 2.2361, 2.4495],
        [1.4142, 3.0000, 2.2361]])

In [105]:
torch.sigmoid(k)

tensor([[0.9997, 0.9933, 0.9975],
        [0.8808, 0.9999, 0.9933]])

In [106]:
torch.softmax(k, dim=0)

tensor([[0.9975, 0.0180, 0.7311],
        [0.0025, 0.9820, 0.2689]])

In [107]:
torch.relu(k)

tensor([[8., 5., 6.],
        [2., 9., 5.]])

In [108]:
### Inplace Operatoins

In [109]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [110]:
print(m)

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])


In [111]:
print(n)

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])


In [112]:
m.add_(n)

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [113]:
m

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [114]:
n

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [115]:
torch.relu(m)

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [116]:
m.relu_()

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [117]:
m

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [118]:
### Copying a Tensor

In [119]:
a = torch.rand(2,3)
a

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [120]:
b = a

In [121]:
b

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [122]:
a[0][0] =0

In [123]:
a

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [124]:
b

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [125]:
id(a)

137720656936496

In [126]:
id(b)

137720656936496

In [127]:
b = a.clone()

In [128]:
a

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [129]:
a[0][0]=10

In [130]:
a

tensor([[10.0000,  0.2131,  0.3957],
        [ 0.6017,  0.4234,  0.5224]])

In [131]:
b

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [132]:
id(a)

137720656936496

In [133]:
id(b)

137720656934288